version: "3"

services:
  # app:
  #   build: .
  #   ports:
  #     - "8083:8082"
  prometheus:
    image: prom/prometheus:v2.33.5
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/workspace/prometheus.yml
    command:
      - "--config.file=/workspace/prometheus.yml"
  grafana:
    image: grafana/grafana:8.4.3
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/datasource.yml:/etc/grafana/provisioning/datasources/default.yml
      - ./monitoring/dashboards.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ./monitoring/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: team4
      GF_INSTALL_PLUGINS: yesoreyeram-infinity-datasource

  load_balancer:
    image: nginx
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8082:8082
    depends_on:
      - app_stable
      - app_next

  app_stable:
    image: "movierecc4:${TAG}"
    ports:
      - 9092:8082
    deploy:
      resources:
        limits:
          memory: 8g

  app_next:
    image: "movierecc4:${TAG}"
    ports:
      - 9093:8082
    deploy:
      resources:
        limits:
          memory: 8g