{
 "title": "flask monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": "flask-api" }
  ]
 },
 "panels": [
  {
   "title": "Reccomendation Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "columns": [
      { "selector": "Timestamp", "text": "Timestamp", "type": "timestamp_epoch_s" },
      { "selector": "Success_Rate", "text": "Success_Rate", "type": "number" }
     ],
     "data": "[ { \"Success_Rate\": 57.03, \"Like_Score\": 0.22, \"Average_Rating\": 0.0, \"Average_WatchTime\": 0.59, \"Success_Rate_Rated_Movie\": 0.0, \"Success_Rate_Watched_Movie\": 57.03, \"Registered_People\": 910, \"Unregistered_People\": 3639, \"Timestamp\": \"1669332525\" } ] ",
     "source": "url",
     "type": "json",
     "url": "http://app:8082/performance",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Reccomendation Average Watch Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "columns": [
      { "selector": "Timestamp", "text": "Timestamp", "type": "timestamp_epoch_s" },
      { "selector": "Average_WatchTime", "text": "Average_WatchTime", "type": "number" }
     ],
     "data": "[ { \"Success_Rate\": 57.03, \"Like_Score\": 0.22, \"Average_Rating\": 0.0, \"Average_WatchTime\": 0.59, \"Success_Rate_Rated_Movie\": 0.0, \"Success_Rate_Watched_Movie\": 57.03, \"Registered_People\": 910, \"Unregistered_People\": 3639, \"Timestamp\": \"1669332525\" } ] ",
     "source": "url",
     "type": "json",
     "url": "http://app:8082/performance",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(flask_http_request_duration_seconds_sum{job=\"flask-api\", path=~\"/recommend/.*\"})"
    }
   ]
  },
  {
   "title": "Reccomendation Average Rating",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "columns": [
      { "selector": "Timestamp", "text": "Timestamp", "type": "timestamp_epoch_s" },
      { "selector": "Average_Rating", "text": "Average_Rating", "type": "number" }
     ],
     "data": "[ { \"Success_Rate\": 57.03, \"Like_Score\": 0.22, \"Average_Rating\": 0.0, \"Average_WatchTime\": 0.59, \"Success_Rate_Rated_Movie\": 0.0, \"Success_Rate_Watched_Movie\": 57.03, \"Registered_People\": 910, \"Unregistered_People\": 3639, \"Timestamp\": \"1669332525\" } ] ",
     "source": "url",
     "type": "json",
     "url": "http://app:8082/performance",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(flask_http_request_duration_seconds_count{job=\"flask-api\", path=~\"/recommend/.*\", status=~\"2.*\"}) by(endpoint, method) / sum(flask_http_request_duration_seconds_count{job=\"flask-api\", path=~\"/recommend/.*\"}) by(endpoint, method)",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum{job=\"flask-api\", path=~\"/recommend/.*\"}/flask_http_request_duration_seconds_count{job=\"flask-api\", path=~\"/recommend/.*\"}",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  }
 ]
}