from model.recbole.model.general_recommender.bpr import BPR
from model.recbole.model.general_recommender.cdae import CDAE
from model.recbole.model.general_recommender.convncf import ConvNCF
from model.recbole.model.general_recommender.dgcf import DGCF
from model.recbole.model.general_recommender.dmf import DMF
from model.recbole.model.general_recommender.ease import EASE
from model.recbole.model.general_recommender.enmf import ENMF
from model.recbole.model.general_recommender.fism import FISM
from model.recbole.model.general_recommender.gcmc import GCMC
from model.recbole.model.general_recommender.itemknn import ItemKNN
from model.recbole.model.general_recommender.lightgcn import LightGCN
from model.recbole.model.general_recommender.line import LINE
from model.recbole.model.general_recommender.macridvae import MacridVAE
from model.recbole.model.general_recommender.multidae import MultiDAE
from model.recbole.model.general_recommender.multivae import MultiVAE
from model.recbole.model.general_recommender.enmf import ENMF
from model.recbole.model.general_recommender.nais import NAIS
from model.recbole.model.general_recommender.neumf import NeuMF
from model.recbole.model.general_recommender.ngcf import NGCF
from model.recbole.model.general_recommender.nncf import NNCF
from model.recbole.model.general_recommender.pop import Pop
from model.recbole.model.general_recommender.ract import RaCT
from model.recbole.model.general_recommender.recvae import RecVAE
from model.recbole.model.general_recommender.slimelastic import SLIMElastic
from model.recbole.model.general_recommender.spectralcf import SpectralCF
from model.recbole.model.general_recommender.nceplrec import NCEPLRec
from model.recbole.model.general_recommender.sgl import SGL
from model.recbole.model.general_recommender.admmslim import ADMMSLIM

